<?PHP

/**
 * Implements hook_install().
 */
function my_module_install() {

// add required terms to the control type vocabulary

$vocab = taxonomy_vocabulary_machine_name_load('control_type');
 
$term1 = (object) array(
 'name' => 'checkbox',
 'description' => 'Checkbox',
 'vid' => $vocab->vid,
);
 
taxonomy_term_save($term1);

$term2 = (object) array(
 'name' => 'radio',
 'description' => 'Radio',
 'vid' => $vocab->vid,
);
 
taxonomy_term_save($term2);

}